source 'https://github.com/CocoaPods/Specs.git'
project 'Aristocrat.xcodeproj'

platform :ios, '9.1'

target "Aristocrat" do

pod 'ZBarSDK', '~> 1.3'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'FontAwesomeIconFactory'
pod 'Firebase/Core'
pod 'SVProgressHUD'

end
